import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import { Footer, Navbar } from '@/components';
import { IoChatbubbleEllipses } from 'react-icons/io5';
import { CartProvider } from '@/context/CartContext';

const popins = Poppins({ subsets: ['latin'], weight: '400' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={popins.className}>
        <CartProvider>
          <Navbar />
          {children}
          <button className="custom_shadow fixed right-[20px] bottom-10 z-50 w-20 h-20 rounded-[50%] bg-primary text-white flex items-center justify-center text-4xl">
            <IoChatbubbleEllipses />
          </button>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
