import type { Metadata } from 'next';
import { Instrument_Sans } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/AuthProvider';
import { LinkProvider } from '@/context/LinkProvider';
import { TabProvider } from '@/context/TabProvider';
import { ProfileProvider } from '@/context/ProfileProvider';

const instrumentSans = Instrument_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

const RootLayout = ({
  children
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body className={instrumentSans.className}>
      <AuthProvider>
        <LinkProvider>
          <TabProvider>
            <ProfileProvider>{children}</ProfileProvider>
          </TabProvider>
        </LinkProvider>
      </AuthProvider>
    </body>
  </html>
);

export default RootLayout;
